POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "TESTI OTSIKKO",
  "author": "TESTI KIRJOITTAJA",
  "url": "http://testi-url.com",
  "likes": "10",
  "userId": "68809be43947060df3eb2413"
}
